utkala.out  : Main.cpp Buyer.o Seller.o Item.o  Purchased.o UTkala.o Read_input.o Consts.o  User.o
	sudo g++ Main.cpp Buyer.o Seller.o Item.o  Purchased.o UTkala.o Read_input.o Consts.o  User.o  --std=c++11 -o utkala.out



UTkala.o: UTkala.cpp UTkala.hpp
	sudo g++ -c  UTkala.cpp

Purchased.o: Purchased.cpp Purchased.hpp
	sudo g++ -c  Purchased.cpp

Item.o: Item.cpp Item.hpp
	sudo g++ -c  Item.cpp

Seller.o : Seller.cpp Seller.hpp
	sudo g++ -c Seller.cpp

Buyer.o: Buyer.cpp Buyer.hpp
	sudo g++ -c Buyer.cpp

User.o : User.cpp User.hpp
	sudo g++ -c  User.cpp

Consts.o: Consts.cpp Consts.hpp
	sudo g++ -c  Consts.cpp

Read_input.o: Read_input.cpp Read_input.hpp
	sudo g++ -c  Read_input.cpp
